name: CI-CD

on: [push, pull_request]

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        mongodb_version: [3.6, 4.0, 4.4]
        python_version: [3.6, 3.9]
        os: [ubuntu-18.04, ubuntu-20.04]
        libgit2_version: [0.26.2]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Checkout Submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          sudo apt-get install -y build-essential wget git
          sudo apt-get install -y python3-cffi
          pip install -U pip setuptools pytest
      - name: Start MongoDB ${{ matrix.mongodb_version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb_version }}
      - name: Install libgit2 ${{ matrix.libgit2_version }}
        run: |
          mkdir libgit2
          cd libgit2
          wget https://github.com/libgit2/libgit2/archive/v${{ matrix.libgit2_version }}.tar.gz
          tar xzf v${{ matrix.libgit2_version }}.tar.gz
          cmake libgit2-${{ matrix.libgit2_version }}/
          make
          sudo make install
          cd ..
      - name: Install Package
        run: |
          python setup.py install
          sudo ldconfig
      - name: Run Tests
        run: |
          pytest

  deploy:
    needs: test-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            mongodb_version: 4.4
            python_version: 3.6
            libgit2_version: 0.26.2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Checkout Submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          sudo apt-get install -y build-essential wget git
          sudo apt-get install -y python3-cffi
          pip install -U pip setuptools pytest
          pip install Sphinx sphinx_rtd_theme
      - name: Start MongoDB ${{ matrix.mongodb_version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb_version }}
      - name: Install libgit2 ${{ matrix.libgit2_version }}
        run: |
          mkdir libgit2
          cd libgit2
          wget https://github.com/libgit2/libgit2/archive/v${{ matrix.libgit2_version }}.tar.gz
          tar xzf v${{ matrix.libgit2_version }}.tar.gz
          cmake libgit2-${{ matrix.libgit2_version }}/
          make
          sudo make install
          cd ..
      - name: Install Package
        run: |
          python setup.py install
          sudo ldconfig
      - name: Run Tests
        run: |
          pytest
      - name: Create Distribution for PyPi
        run: |
          python setup.py sdist --dist-dir release_dist
      - name: Build Plugin
        run: |
          cd plugin_packaging
          chmod +rx build_plugin.sh
          ./build_plugin.sh
          cd ..
      - name: Make Documentation
        run: |
          make html
      - name: Publish on PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: release_dist/
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: plugin_packaging/vcsSHARK_plugin.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Documentation on GH-Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
